# Generated by Django 2.0.5 on 2018-05-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('uni_uuid', models.CharField(max_length=40, unique=True)),
                ('create_time', models.CharField(max_length=40)),
                ('update_time', models.CharField(max_length=40)),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('url', models.CharField(max_length=225)),
                ('use', models.BooleanField(help_text='是否使用')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('uni_uuid', models.CharField(max_length=40, unique=True)),
                ('create_time', models.CharField(max_length=40)),
                ('update_time', models.CharField(max_length=40)),
                ('rank_type', models.CharField(db_index=True, max_length=10)),
            ],
        ),
    ]
